"""Jira Cloud REST API v3 ticket provider."""

import json
import logging
import os
from typing import Any

import requests

from api.ticketing.base import TicketProvider

logger = logging.getLogger(__name__)


def safe_json_loads(v, default=None):
    if default is None:
        default = []
    if not v:
        return default
    try:
        return json.loads(v)
    except Exception:
        return default


class JiraProvider(TicketProvider):
    """Creates Jira issues via the Jira Cloud REST API v3."""

    def __init__(self) -> None:
        self.base_url    = os.getenv("JIRA_BASE_URL", "").rstrip("/")
        self.email       = os.getenv("JIRA_EMAIL", "")
        self.api_token   = os.getenv("JIRA_API_TOKEN", "")
        self.project_key = os.getenv("JIRA_PROJECT_KEY", "SEC")
        self.issue_type  = os.getenv("JIRA_ISSUE_TYPE", "Task")
        self.verify_tls  = os.getenv("JIRA_VERIFY_TLS", "true").lower() != "false"
        self.timeout     = int(os.getenv("JIRA_TIMEOUT_SECONDS", "15"))

        if not all([self.base_url, self.email, self.api_token]):
            raise ValueError(
                "Jira provider requires JIRA_BASE_URL, JIRA_EMAIL, and JIRA_API_TOKEN "
                "environment variables."
            )

    def _auth(self) -> tuple[str, str]:
        return (self.email, self.api_token)

    def _build_description(self, job: dict) -> dict:
        cve_list = safe_json_loads(job.get("cve_list"), [])
        kev_cves = safe_json_loads(job.get("kev_cves"), [])
        cve_bullets = "\n".join(f"* {c}" for c in cve_list) or "_None_"

        text = (
            f"*VRA Automated Remediation Job*\n\n"
            f"*Risk Level:* {job.get('max_risk_level', 'N/A')}\n"
            f"*Risk Score:* {job.get('risk_score_max', 'N/A')}\n"
            f"*SLA Due Date:* {job.get('due_date', 'N/A')}\n"
            f"*Environment:* {job.get('environment', 'N/A')}\n"
            f"*Business Unit:* {job.get('business_unit', 'N/A')}\n"
            f"*Business Owner:* {job.get('business_owner', 'N/A')}\n\n"
            f"*CVEs ({len(cve_list)}):*\n{cve_bullets}\n\n"
        )
        if kev_cves:
            text += f"*⚠ KEV CVEs:* {', '.join(kev_cves)}\n\n"

        text += f"_Generated by VRA — job_id: {job.get('job_id')}_"

        return {
            "type":    "doc",
            "version": 1,
            "content": [
                {
                    "type":    "paragraph",
                    "content": [{"type": "text", "text": text}],
                }
            ],
        }

    def create_ticket(self, job: dict) -> dict:
        summary = (
            f"[VRA] {job.get('main_product', 'Unknown')} — "
            f"{job.get('max_risk_level', 'N/A')}"
        )

        payload: dict[str, Any] = {
            "fields": {
                "project":     {"key": self.project_key},
                "summary":     summary,
                "description": self._build_description(job),
                "issuetype":   {"name": self.issue_type},
                "labels":      ["vra", "security", job.get("max_risk_level", "").lower()],
            }
        }

        url = f"{self.base_url}/rest/api/3/issue"
        response = requests.post(
            url,
            auth=self._auth(),
            json=payload,
            headers={"Accept": "application/json", "Content-Type": "application/json"},
            verify=self.verify_tls,
            timeout=self.timeout,
        )

        if not response.ok:
            logger.error(
                "Jira API error %d: %s", response.status_code, response.text[:500]
            )
            response.raise_for_status()

        data = response.json()
        issue_key = data["key"]
        ticket_url = f"{self.base_url}/browse/{issue_key}"

        logger.info("Jira ticket created: %s → %s", issue_key, ticket_url)
        return {
            "ticket_id":  issue_key,
            "ticket_url": ticket_url,
            "provider":   "jira",
        }
